In [1]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, roc_auc_score

In [2]:
airline=pd.read_csv('airline.csv')

In [3]:
airline

,YEAR,MONTH,DAY_OF_MONTH,DAY_OF_WEEK,FL_DATE,OP_UNIQUE_CARRIER,OP_CARRIER_FL_NUM,ORIGIN,ORIGIN_CITY_NAME,ORIGIN_STATE_ABR,...,CRS_ELAPSED_TIME,ACTUAL_ELAPSED_TIME,AIR_TIME,FLIGHTS,DISTANCE,CARRIER_DELAY,WEATHER_DELAY,NAS_DELAY,SECURITY_DELAY,LATE_AIRCRAFT_DELAY
0,2025,1,1,3,1/1/2025 12:00:00 AM,AA,1,JFK,"New York, NY",NY,...,381.0,377.0,345.0,1.0,2475.0,NaN,NaN,NaN,NaN,NaN
1,2025,1,1,3,1/1/2025 12:00:00 AM,AA,10,LAX,"Los Angeles, CA",CA,...,330.0,290.0,274.0,1.0,2475.0,NaN,NaN,NaN,NaN,NaN
2,2025,1,1,3,1/1/2025 12:00:00 AM,AA,1002,MSN,"Madison, WI",WI,...,141.0,125.0,91.0,1.0,708.0,20.0,0.0,0.0,0.0,0.0
3,2025,1,1,3,1/1/2025 12:00:00 AM,AA,1004,PHL,"Philadelphia, PA",PA,...,339.0,331.0,306.0,1.0,2176.0,NaN,NaN,NaN,NaN,NaN
4,2025,1,1,3,1/1/2025 12:00:00 AM,AA,1005,ORD,"Chicago, IL",IL,...,241.0,286.0,212.0,1.0,1440.0,0.0,0.0,44.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
539742,2025,1,31,5,1/31/2025 12:00:00 AM,YX,5858,DCA,"Washington, DC",VA,...,80.0,76.0,53.0,1.0,213.0,NaN,NaN,NaN,NaN,NaN
539743,2025,1,31,5,1/31/2025 12:00:00 AM,YX,5860,MCO,"Orlando, FL",FL,...,110.0,97.0,77.0,1.0,534.0,NaN,NaN,NaN,NaN,NaN
539744,2025,1,31,5,1/31/2025 12:00:00 AM,YX,5861,CMH,"Columbus, OH",OH,...,111.0,105.0,82.0,1.0,479.0,NaN,NaN,NaN,NaN,NaN
539745,2025,1,31,5,1/31/2025 12:00:00 AM,YX,5862,RDU,"Raleigh/Durham, NC",NC,...,119.0,105.0,85.0,1.0,534.0,NaN,NaN,NaN,NaN,NaN
539746,2025,1,31,5,1/31/2025 12:00:00 AM,YX,5863,RDU,"Raleigh/Durham, NC",NC,...,106.0,96.0,69.0,1.0,431.0,NaN,NaN,NaN,NaN,NaN

In [4]:
airline.isnull().sum()

YEAR                        0
MONTH                       0
DAY_OF_MONTH                0
DAY_OF_WEEK                 0
FL_DATE                     0
OP_UNIQUE_CARRIER           0
OP_CARRIER_FL_NUM           0
ORIGIN                      0
ORIGIN_CITY_NAME            0
ORIGIN_STATE_ABR            0
DEST                        0
DEST_CITY_NAME              0
DEST_STATE_NM               0
CRS_DEP_TIME                0
DEP_TIME                15886
DEP_DELAY               15923
DEP_DELAY_NEW           15923
DEP_DEL15               15923
DEP_TIME_BLK                0
TAXI_OUT                16227
TAXI_IN                 16580
CRS_ARR_TIME                0
ARR_TIME                16580
ARR_DELAY               17478
ARR_DELAY_NEW           17478
ARR_DEL15               17478
ARR_TIME_BLK                0
CANCELLED                   0
CANCELLATION_CODE      523435
DIVERTED                    0
CRS_ELAPSED_TIME            0
ACTUAL_ELAPSED_TIME     17478
AIR_TIME                17478
FLIGHTS                     0
DISTANCE                    0
CARRIER_DELAY          441617
WEATHER_DELAY          441617
NAS_DELAY              441617
SECURITY_DELAY         441617
LATE_AIRCRAFT_DELAY    441617
dtype: int64

In [6]:
airline.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 539747 entries, 0 to 539746
Data columns (total 40 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   YEAR                 539747 non-null  int64
 1   MONTH                539747 non-null  int64
 2   DAY_OF_MONTH         539747 non-null  int64
 3   DAY_OF_WEEK          539747 non-null  int64
 4   FL_DATE              539747 non-null  object
 5   OP_UNIQUE_CARRIER    539747 non-null  object
 6   OP_CARRIER_FL_NUM    539747 non-null  int64
 7   ORIGIN               539747 non-null  object
 8   ORIGIN_CITY_NAME     539747 non-null  object
 9   ORIGIN_STATE_ABR     539747 non-null  object
 10  DEST                 539747 non-null  object
 11  DEST_CITY_NAME       539747 non-null  object
 12  DEST_STATE_NM        539747 non-null  object
 13  CRS_DEP_TIME         539747 non-null  int64
 14  DEP_TIME             523861 non-null  float64
 15  DEP_DELAY            523824 non-null  float64
 16  DEP_DELAY_NEW        523824 non-null  float64
 17  DEP_DEL15            523824 non-null  float64
 18  DEP_TIME_BLK         539747 non-null  object
 19  TAXI_OUT             523520 non-null  float64
 20  TAXI_IN              523167 non-null  float64
 21  CRS_ARR_TIME         539747 non-null  int64
 22  ARR_TIME             523167 non-null  float64
 23  ARR_DELAY            522269 non-null  float64
 24  ARR_DELAY_NEW        522269 non-null  float64
 25  ARR_DEL15            522269 non-null  float64
 26  ARR_TIME_BLK         539747 non-null  object
 27  CANCELLED            539747 non-null  float64
 28  CANCELLATION_CODE    16312 non-null   object
 29  DIVERTED             539747 non-null  float64
 30  CRS_ELAPSED_TIME     539747 non-null  float64
 31  ACTUAL_ELAPSED_TIME  522269 non-null  float64
 32  AIR_TIME             522269 non-null  float64
 33  FLIGHTS              539747 non-null  float64
 34  DISTANCE             539747 non-null  float64
 35  CARRIER_DELAY        98130 non-null   float64
 36  WEATHER_DELAY        98130 non-null   float64
 37  NAS_DELAY            98130 non-null   float64
 38  SECURITY_DELAY       98130 non-null   float64
 39  LATE_AIRCRAFT_DELAY  98130 non-null   float64
dtypes: float64(22), int64(7), object(11)
memory usage: 164.7+ MB

In [7]:
airline.duplicated().sum()

np.int64(0)

In [10]:
delay_columns=[
    "CARRIER_DELAY",
    "WEATHER_DELAY",
    "NAS_DELAY",
    "SECURITY_DELAY",
    "LATE_AIRCRAFT_DELAY"
]

airline[delay_columns]=airline[delay_columns].fillna(0)

In [11]:
airline

,YEAR,MONTH,DAY_OF_MONTH,DAY_OF_WEEK,FL_DATE,OP_UNIQUE_CARRIER,OP_CARRIER_FL_NUM,ORIGIN,ORIGIN_CITY_NAME,ORIGIN_STATE_ABR,...,CRS_ELAPSED_TIME,ACTUAL_ELAPSED_TIME,AIR_TIME,FLIGHTS,DISTANCE,CARRIER_DELAY,WEATHER_DELAY,NAS_DELAY,SECURITY_DELAY,LATE_AIRCRAFT_DELAY
0,2025,1,1,3,1/1/2025 12:00:00 AM,AA,1,JFK,"New York, NY",NY,...,381.0,377.0,345.0,1.0,2475.0,0.0,0.0,0.0,0.0,0.0
1,2025,1,1,3,1/1/2025 12:00:00 AM,AA,10,LAX,"Los Angeles, CA",CA,...,330.0,290.0,274.0,1.0,2475.0,0.0,0.0,0.0,0.0,0.0
2,2025,1,1,3,1/1/2025 12:00:00 AM,AA,1002,MSN,"Madison, WI",WI,...,141.0,125.0,91.0,1.0,708.0,20.0,0.0,0.0,0.0,0.0
3,2025,1,1,3,1/1/2025 12:00:00 AM,AA,1004,PHL,"Philadelphia, PA",PA,...,339.0,331.0,306.0,1.0,2176.0,0.0,0.0,0.0,0.0,0.0
4,2025,1,1,3,1/1/2025 12:00:00 AM,AA,1005,ORD,"Chicago, IL",IL,...,241.0,286.0,212.0,1.0,1440.0,0.0,0.0,44.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
539742,2025,1,31,5,1/31/2025 12:00:00 AM,YX,5858,DCA,"Washington, DC",VA,...,80.0,76.0,53.0,1.0,213.0,0.0,0.0,0.0,0.0,0.0
539743,2025,1,31,5,1/31/2025 12:00:00 AM,YX,5860,MCO,"Orlando, FL",FL,...,110.0,97.0,77.0,1.0,534.0,0.0,0.0,0.0,0.0,0.0
539744,2025,1,31,5,1/31/2025 12:00:00 AM,YX,5861,CMH,"Columbus, OH",OH,...,111.0,105.0,82.0,1.0,479.0,0.0,0.0,0.0,0.0,0.0
539745,2025,1,31,5,1/31/2025 12:00:00 AM,YX,5862,RDU,"Raleigh/Durham, NC",NC,...,119.0,105.0,85.0,1.0,534.0,0.0,0.0,0.0,0.0,0.0
539746,2025,1,31,5,1/31/2025 12:00:00 AM,YX,5863,RDU,"Raleigh/Durham, NC",NC,...,106.0,96.0,69.0,1.0,431.0,0.0,0.0,0.0,0.0,0.0

In [12]:
airline.isnull().sum()

YEAR                        0
MONTH                       0
DAY_OF_MONTH                0
DAY_OF_WEEK                 0
FL_DATE                     0
OP_UNIQUE_CARRIER           0
OP_CARRIER_FL_NUM           0
ORIGIN                      0
ORIGIN_CITY_NAME            0
ORIGIN_STATE_ABR            0
DEST                        0
DEST_CITY_NAME              0
DEST_STATE_NM               0
CRS_DEP_TIME                0
DEP_TIME                15886
DEP_DELAY               15923
DEP_DELAY_NEW           15923
DEP_DEL15               15923
DEP_TIME_BLK                0
TAXI_OUT                16227
TAXI_IN                 16580
CRS_ARR_TIME                0
ARR_TIME                16580
ARR_DELAY               17478
ARR_DELAY_NEW           17478
ARR_DEL15               17478
ARR_TIME_BLK                0
CANCELLED                   0
CANCELLATION_CODE      523435
DIVERTED                    0
CRS_ELAPSED_TIME            0
ACTUAL_ELAPSED_TIME     17478
AIR_TIME                17478
FLIGHTS                     0
DISTANCE                    0
CARRIER_DELAY               0
WEATHER_DELAY               0
NAS_DELAY                   0
SECURITY_DELAY              0
LATE_AIRCRAFT_DELAY         0
dtype: int64

In [13]:
remove_null=["DEP_TIME","DEP_DELAY","DEP_DELAY_NEW","DEP_DEL15","TAXI_OUT","TAXI_IN","ARR_TIME","ARR_DELAY","ARR_DELAY_NEW","ARR_DEL15"
             ,"CANCELLATION_CODE","ACTUAL_ELAPSED_TIME","AIR_TIME"]

In [14]:
airline[remove_null]=airline[remove_null].fillna(0)

In [15]:
airline.isnull().sum()

YEAR                   0
MONTH                  0
DAY_OF_MONTH           0
DAY_OF_WEEK            0
FL_DATE                0
OP_UNIQUE_CARRIER      0
OP_CARRIER_FL_NUM      0
ORIGIN                 0
ORIGIN_CITY_NAME       0
ORIGIN_STATE_ABR       0
DEST                   0
DEST_CITY_NAME         0
DEST_STATE_NM          0
CRS_DEP_TIME           0
DEP_TIME               0
DEP_DELAY              0
DEP_DELAY_NEW          0
DEP_DEL15              0
DEP_TIME_BLK           0
TAXI_OUT               0
TAXI_IN                0
CRS_ARR_TIME           0
ARR_TIME               0
ARR_DELAY              0
ARR_DELAY_NEW          0
ARR_DEL15              0
ARR_TIME_BLK           0
CANCELLED              0
CANCELLATION_CODE      0
DIVERTED               0
CRS_ELAPSED_TIME       0
ACTUAL_ELAPSED_TIME    0
AIR_TIME               0
FLIGHTS                0
DISTANCE               0
CARRIER_DELAY          0
WEATHER_DELAY          0
NAS_DELAY              0
SECURITY_DELAY         0
LATE_AIRCRAFT_DELAY    0
dtype: int64

In [17]:
airline.shape

(539747, 40)

In [18]:
airline.shape
airline.duplicated().sum()

np.int64(0)

In [19]:
airline.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 539747 entries, 0 to 539746
Data columns (total 40 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   YEAR                 539747 non-null  int64
 1   MONTH                539747 non-null  int64
 2   DAY_OF_MONTH         539747 non-null  int64
 3   DAY_OF_WEEK          539747 non-null  int64
 4   FL_DATE              539747 non-null  object
 5   OP_UNIQUE_CARRIER    539747 non-null  object
 6   OP_CARRIER_FL_NUM    539747 non-null  int64
 7   ORIGIN               539747 non-null  object
 8   ORIGIN_CITY_NAME     539747 non-null  object
 9   ORIGIN_STATE_ABR     539747 non-null  object
 10  DEST                 539747 non-null  object
 11  DEST_CITY_NAME       539747 non-null  object
 12  DEST_STATE_NM        539747 non-null  object
 13  CRS_DEP_TIME         539747 non-null  int64
 14  DEP_TIME             539747 non-null  float64
 15  DEP_DELAY            539747 non-null  float64
 16  DEP_DELAY_NEW        539747 non-null  float64
 17  DEP_DEL15            539747 non-null  float64
 18  DEP_TIME_BLK         539747 non-null  object
 19  TAXI_OUT             539747 non-null  float64
 20  TAXI_IN              539747 non-null  float64
 21  CRS_ARR_TIME         539747 non-null  int64
 22  ARR_TIME             539747 non-null  float64
 23  ARR_DELAY            539747 non-null  float64
 24  ARR_DELAY_NEW        539747 non-null  float64
 25  ARR_DEL15            539747 non-null  float64
 26  ARR_TIME_BLK         539747 non-null  object
 27  CANCELLED            539747 non-null  float64
 28  CANCELLATION_CODE    539747 non-null  object
 29  DIVERTED             539747 non-null  float64
 30  CRS_ELAPSED_TIME     539747 non-null  float64
 31  ACTUAL_ELAPSED_TIME  539747 non-null  float64
 32  AIR_TIME             539747 non-null  float64
 33  FLIGHTS              539747 non-null  float64
 34  DISTANCE             539747 non-null  float64
 35  CARRIER_DELAY        539747 non-null  float64
 36  WEATHER_DELAY        539747 non-null  float64
 37  NAS_DELAY            539747 non-null  float64
 38  SECURITY_DELAY       539747 non-null  float64
 39  LATE_AIRCRAFT_DELAY  539747 non-null  float64
dtypes: float64(22), int64(7), object(11)
memory usage: 164.7+ MB

In [21]:
airline["FL_DATE"] = pd.to_datetime(airline["FL_DATE"],format="%m/%d/%Y")

In [22]:
airline.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 539747 entries, 0 to 539746
Data columns (total 40 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   YEAR                 539747 non-null  int64
 1   MONTH                539747 non-null  int64
 2   DAY_OF_MONTH         539747 non-null  int64
 3   DAY_OF_WEEK          539747 non-null  int64
 4   FL_DATE              539747 non-null  datetime64[ns]
 5   OP_UNIQUE_CARRIER    539747 non-null  object
 6   OP_CARRIER_FL_NUM    539747 non-null  int64
 7   ORIGIN               539747 non-null  object
 8   ORIGIN_CITY_NAME     539747 non-null  object
 9   ORIGIN_STATE_ABR     539747 non-null  object
 10  DEST                 539747 non-null  object
 11  DEST_CITY_NAME       539747 non-null  object
 12  DEST_STATE_NM        539747 non-null  object
 13  CRS_DEP_TIME         539747 non-null  int64
 14  DEP_TIME             539747 non-null  float64
 15  DEP_DELAY            539747 non-null  float64
 16  DEP_DELAY_NEW        539747 non-null  float64
 17  DEP_DEL15            539747 non-null  float64
 18  DEP_TIME_BLK         539747 non-null  object
 19  TAXI_OUT             539747 non-null  float64
 20  TAXI_IN              539747 non-null  float64
 21  CRS_ARR_TIME         539747 non-null  int64
 22  ARR_TIME             539747 non-null  float64
 23  ARR_DELAY            539747 non-null  float64
 24  ARR_DELAY_NEW        539747 non-null  float64
 25  ARR_DEL15            539747 non-null  float64
 26  ARR_TIME_BLK         539747 non-null  object
 27  CANCELLED            539747 non-null  float64
 28  CANCELLATION_CODE    539747 non-null  object
 29  DIVERTED             539747 non-null  float64
 30  CRS_ELAPSED_TIME     539747 non-null  float64
 31  ACTUAL_ELAPSED_TIME  539747 non-null  float64
 32  AIR_TIME             539747 non-null  float64
 33  FLIGHTS              539747 non-null  float64
 34  DISTANCE             539747 non-null  float64
 35  CARRIER_DELAY        539747 non-null  float64
 36  WEATHER_DELAY        539747 non-null  float64
 37  NAS_DELAY            539747 non-null  float64
 38  SECURITY_DELAY       539747 non-null  float64
 39  LATE_AIRCRAFT_DELAY  539747 non-null  float64
dtypes: datetime64[ns](1), float64(22), int64(7), object(10)
memory usage: 164.7+ MB

In [23]:
airline["DIVERTED"].value_counts()

DIVERTED
0.0    538581
1.0      1166
Name: count, dtype: int64

In [24]:
airline["CANCELLED"].value_counts()

CANCELLED
0.0    523435
1.0     16312
Name: count, dtype: int64

In [25]:
airline[airline["DISTANCE"] <= 0].shape

(0, 40)

In [26]:
airline[airline["CRS_ELAPSED_TIME"] <= 0].shape

(0, 40)

In [27]:
airline[airline["AIR_TIME"] < 0].shape

(0, 40)

In [28]:
airline["ARR_DELAY"].describe()

count    539747.000000
mean          3.634968
std          55.926793
min         -87.000000
25%         -18.000000
50%          -7.000000
75%           6.000000
max        3282.000000
Name: ARR_DELAY, dtype: float64

In [29]:
airline["DEP_DELAY"].describe()

count    539747.000000
mean         10.035746
std          53.549570
min         -50.000000
25%          -6.000000
50%          -3.000000
75%           6.000000
max        3298.000000
Name: DEP_DELAY, dtype: float64

In [33]:
airline.shape

(539747, 40)

In [31]:
airline["OP_UNIQUE_CARRIER"].nunique()

14

In [32]:
airline["ORIGIN"].nunique()

329

In [34]:
airline["DEST"].nunique()

329

In [35]:
airline["ARR_DEL15"].value_counts()

ARR_DEL15
0.0    441617
1.0     98130
Name: count, dtype: int64

In [36]:
airline["ARR_DEL15"].value_counts(normalize=True) * 100

ARR_DEL15
0.0    81.81926
1.0    18.18074
Name: proportion, dtype: float64

In [37]:
airline.groupby("OP_UNIQUE_CARRIER")["ARR_DEL15"].mean()

OP_UNIQUE_CARRIER
AA    0.184583
AS    0.172714
B6    0.239647
DL    0.187430
F9    0.252802
G4    0.233601
HA    0.132436
MQ    0.175377
NK    0.174647
OH    0.231345
OO    0.203902
UA    0.172464
WN    0.147483
YX    0.153559
Name: ARR_DEL15, dtype: float64

In [38]:
airline.groupby("ORIGIN")["ARR_DEL15"].mean().sort_values(ascending=False)

ORIGIN
CKB    0.777778
SCE    0.562500
TOL    0.451613
SMX    0.444444
COD    0.403226
         ...
YUM    0.062937
PIH    0.049180
EKO    0.032258
PQI    0.000000
OTH    0.000000
Name: ARR_DEL15, Length: 329, dtype: float64

In [39]:
airline.groupby("DEST")["ARR_DEL15"].mean().sort_values(ascending=False)

DEST
CKB    0.555556
SCE    0.500000
USA    0.460000
SHR    0.403226
COD    0.403226
         ...
MEI    0.055556
PIH    0.032787
EKO    0.000000
OTH    0.000000
OTZ    0.000000
Name: ARR_DEL15, Length: 329, dtype: float64

In [40]:
airline.groupby(["ORIGIN", "DEST"])["ARR_DEL15"].mean()

ORIGIN  DEST
ABE     BNA     0.000000
        CLT     0.150538
        FLL     0.700000
        MCO     0.111111
        MLB     0.111111
                  ...
XWA     MSP     0.373134
YAK     CDV     0.133333
        JNU     0.033333
YUM     DFW     0.129032
        PHX     0.044643
Name: ARR_DEL15, Length: 5649, dtype: float64

In [41]:
airline.groupby("MONTH")["ARR_DEL15"].mean()

MONTH
1    0.181807
Name: ARR_DEL15, dtype: float64

In [42]:
airline.groupby("DAY_OF_WEEK")["ARR_DEL15"].mean()

DAY_OF_WEEK
1    0.218708
2    0.147772
3    0.129757
4    0.166632
5    0.187196
6    0.212676
7    0.218121
Name: ARR_DEL15, dtype: float64

In [43]:
airline.groupby("DEP_TIME_BLK")["ARR_DEL15"].mean()

DEP_TIME_BLK
0001-0559    0.120188
0600-0659    0.120962
0700-0759    0.141819
0800-0859    0.150556
0900-0959    0.151970
1000-1059    0.167325
1100-1159    0.170905
1200-1259    0.183511
1300-1359    0.186019
1400-1459    0.199232
1500-1559    0.209925
1600-1659    0.213163
1700-1759    0.212876
1800-1859    0.216787
1900-1959    0.223154
2000-2059    0.225446
2100-2159    0.219536
2200-2259    0.204642
2300-2359    0.141586
Name: ARR_DEL15, dtype: float64

In [44]:
delay_columns = [
    "CARRIER_DELAY",
    "WEATHER_DELAY",
    "NAS_DELAY",
    "SECURITY_DELAY",
    "LATE_AIRCRAFT_DELAY"
]

airline[delay_columns].sum()

CARRIER_DELAY          2510886.0
WEATHER_DELAY           629972.0
NAS_DELAY              1381827.0
SECURITY_DELAY           10550.0
LATE_AIRCRAFT_DELAY    2410759.0
dtype: float64

In [45]:
airline.to_csv("airline_cleaned.csv", index=False)